### ISSUE TITLE
Change reclaim_manifest.jps to create and modify jupyter_server_config.py

### ISSUE THREAD

**Issue by wragge** [GLAM-Workbench/glam-workbench.github.io#47]
Currently the Reclaim install script gets a password, hashes it, then adds it to the Jupyter server config by modifying the entry point.

This works ok, but it's a pain if the user ever wants to change the password. An alternative is to generate and modify the `jupyter_server_config.py` file to set the password.

I can also use this method to set other configuration options such as the default url.

I've tested the script below and it seems to work ok. Need to roll it out across repos.

```yaml
type: install
name: Trove Newspaper Harvester (GLAM Workbench)

settings:
    fields:
      - hideLabel: false
        hidden: false
        type: string
        inputType: password
        required: true
        caption: Set a password for Jupyter
        name: jupyterPassword

onInstall:
    - cmd[cp]: jupyter server --generate-config
    - cmd[cp]: sed -i "s|# c.ServerApp.default_url = '/'|c.ServerApp.default_url = '/lab/tree/index.md'|" /home/jovyan/.jupyter/jupyter_server_config.py
    - cmd[cp]: python3 -c "from notebook.auth import passwd; print(passwd('${settings.jupyterPassword}', 'sha1'))"
    - cmd[cp]: sed -i "s|# c.ServerApp.password = ''|c.ServerApp.password = '${response.out}'|" /home/jovyan/.jupyter/jupyter_server_config.py
    - cmd[cp]: chown -R jovyan:jovyan /home/jovyan/work
    - api:
        - method: environment.control.SetContainerRunCmd
          params:
            nodeId: ${nodes.cp[0].id}
            data: "jupyter lab --ip 0.0.0.0"
        - method: environment.control.RestartNodes
          params:
            nodeGroup: cp
nodes:
    nodeGroup: cp
    cloudlets: 16
    image: "glamworkbench/trove-newspaper-harvester:latest"
    entrypoint: /usr/local/bin/repo2docker-entrypoint
    volumes:
        - /home/jovyan/work

ssl: true
success: |
  **Juyter notebook URL**: [https://${env.domain}/](https://${env.domain}/)
  **Password**: ${settings.jupyterPassword}
```
